### PR TITLE
3.5.0.2

### PR DESCRIPTION
**Pull request by tryallthethings**

### CODE REVIEW

**Comment by tryallthethings** [comment]
@Rillke Do you want to review the changes?

**Review by Rillke — APPROVED** [review]
Seems to be user-tested by someone in #14, and I can see plenty of improvements. Thanks.

**Comment by Rillke** [comment]
On the long run, we could move the conversion code out from the forms (e.g. Form1.cs) into separate classes so we can properly unit test im- and export formats and options during CI and add specification to it. Otherwise detecting incompatible changes in the conversion process will be difficult to spot given the increase in options. Thanks for squashing some bugs.

**Comment by tryallthethings** [comment]
The version was also tested in #9 and #10 :wink: 
Having it as separate classes makes sense although that seems like a major rewrite (especially the export could use some streamlining). Unit tests and CI are things I haven't worked with yet.

**Pull request merged**
